persistence:
  defaultStore: cass-default
  visibilityStore: cass-visibility
  numHistoryShards: 4
  datastores:
    cass-default:
      cassandra:
        hosts: "127.0.0.1"
        keyspace: "cadence"
        consistency: "One"
    cass-visibility:
      cassandra:
        hosts: "127.0.0.1"
        keyspace: "cadence_visibility"
        consistency: "One"

ringpop:
  name: cadence
  bootstrapMode: hosts
  bootstrapHosts: ["127.0.0.1:7933", "127.0.0.1:7934", "127.0.0.1:7935"]
  maxJoinDuration: 30s

services:
  frontend:
    rpc:
      port: 7933
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7936

  matching:
    rpc:
      port: 7935
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7938

  history:
    rpc:
      port: 7934
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7937

  worker:
    rpc:
      port: 7939
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 7940

clustersInfo:
  enableGlobalDomain: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInitialFailoverVersion:
    active: 0
  clusterAddress:
    active:
      rpcName: "cadence-frontend"
      rpcAddress: "127.0.0.1:7933"

dcRedirectionPolicy:
  policy: "noop"
  toDC: ""

archival:
  enabled: true
  filestore:
    storeDirectory: "/tmp/development/blobstore/"
    defaultBucket:
      name: "cadence-development"
      owner: "cadence"
      retentionDays: 10
    customBuckets:
      - name: "custom-bucket-1"
        owner: "custom-owner-1"
        retentionDays: 10
      - name: "custom-bucket-2"
        owner: "custom-owner-2"
        retentionDays: 5

kafka:
  clusters:
    test:
      brokers:
        - 127.0.0.1:9092
  topics:
    cadence-visibility-dev:
      cluster: test
    cadence-visibility-dev-dlq:
      cluster: test
  applications:
    visibility:
      topic: cadence-visibility-dev
      dlq-topic: cadence-visibility-dev-dlq

elasticsearch:
  enable: false
  url:
    scheme: "http"
    host: "127.0.0.1:9200"
  indices:
    visibility: cadence-visibility-dev

